# Generated by Django 5.0.4 on 2024-05-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=2)),
                ('place', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('class_no', models.IntegerField()),
                ('phone', models.CharField(max_length=10)),
                ('photos', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
