# Generated by Django 5.1.4 on 2024-12-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djang_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='age',
        ),
        migrations.RemoveField(
            model_name='school',
            name='class_no',
        ),
        migrations.RemoveField(
            model_name='school',
            name='email',
        ),
        migrations.RemoveField(
            model_name='school',
            name='name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='school',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='school',
            name='place',
        ),
        migrations.AddField(
            model_name='school',
            name='Sponsor_Name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='study_Description',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='study_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='study_phase',
            field=models.IntegerField(blank=True, choices=[(1, 'phase I'), (2, 'phase II'), (3, 'phase III'), (4, 'phase IV')], null=True),
        ),
    ]
